### ISSUE TITLE
Question: What version of Python is this coded in/for?

### ISSUE THREAD

**Issue by vdalv** [MichaelOultram/Labyrinth#1]
I'm having issues with both versions (2.7 and 3.3), and want to know which one I should use to continue debugging.

Thanks

**Comment by MichaelOultram** [comment]
Wow, I wasn't actually expecting somebody to run my code (especially this fast). 

I have been running using Python 3.6.2 on my local machine. My code uses asserts to check user input is valid (instead of a more user friendly way) which could be the cause of some of the crashes. I have added a Dockerfile to the repo in case that helps you to get this app working.

If you need any more help, post the stacktraces and I can look into it.

**Comment by vdalv** [comment]
Looks like installing 3.6.2 cleared up the issues I was having, thanks.
