### ISSUE TITLE
Tiles not displaying properly

### ISSUE THREAD

**Issue by vdalv** [MichaelOultram/Labyrinth#2]
When running the program via IDLE or cmd prompt, some of the tiles aren't appearing properly (screenshots below).

EDIT: As evidenced by the screenshots, I'm using Windows 7

![IDLE](http://i.imgur.com/sU2f8J1.png)
![CMD](http://i.imgur.com/UzZBIx0.png)

**Comment by MichaelOultram** [comment]
It looks like your terminal doesn't support ANSI colouring. I have made a push that allows you to turn off the colouring but this will make it very difficult to see where the players are standing (you can look at the coordinates of each player printed below the board).

You may be able to get the colours to display if you try the [git bash terminal](https://git-for-windows.github.io/) (or some other terminal that supports ANSI colour encoding)

EDIT: As a point of reference, this is what it looks like for me
![2017-08-17-002156_1076x940_scrot](https://user-images.githubusercontent.com/9907700/29389478-397a4342-82e2-11e7-8749-619e2958cae4.png)

**Comment by vdalv** [comment]
Hmmm, yeah, w/o the colors it's pretty difficult to play. There's only some '←[0m' characters to assist you...

![](http://i.imgur.com/EvFcCrr.png)

git-bash can do colors, but is having a [different issue](https://github.com/MichaelOultram/Labyrinth/issues/3).

**Comment by MichaelOultram** [comment]
Those ←[0m characters shouldn't really be shown and I think I've fixed that in the latest commit (but I haven't yet tested it). 

I have also made a change so that the letter of the player is displayed in the corner on the tile they are standing on. It is not that easy to spot, but it may help if the terminal colours don't work.

**Comment by vdalv** [comment]
Alright, looks good now. Neat idea w/ the letters.
![](http://i.imgur.com/UwvUlq6.png)

I was curious about the "Do not choose <t/b/l/r> <left/middle/right>" messages, so I chose the place it told me not to...that was a pretty interesting reaction.

**Comment by MichaelOultram** [comment]
The reason for the "Do not choose ..." is because there is a rule in the game that you cannot "undo" the previous push (i.e. if the last player pushed left top, then the next player cannot push right top). 

I shouldn't really be using asserts to check user input; it was just quicker to code. ~~I'll probably change it to a more user friendly way soon~~ I have made this change.

**Comment by vdalv** [comment]
"Cannot slide the tile in that direction"

Looks good.
