### ISSUE TITLE
git-bash crash

### ISSUE THREAD

**Issue by vdalv** [MichaelOultram/Labyrinth#3]
Crashes when running on git-bash, regardless of colors on/off. Too tired atm to investigate myself.

![](http://i.imgur.com/BFOI6Jy.png)
![](http://i.imgur.com/1xs3mzo.png)

**Comment by MichaelOultram** [comment]
After a bit of trial and error, I have managed to get it to run using git bash under windows 10. First make sure that the terminal is using utf8 encodings. Right click the terminal -> Options -> Text -> set Character Set to utf8. Close and reopen git bash (so that it picks up the changes).

Next you need to set the environment variable `PYTHONIOENCODING` to `utf8` to tell python that it can print in utf8. The easiest way to do this is to run the game using `PYTHONIOENCODING=utf8 python interactive_labyrinth.py`. A more permanent solution is to run `echo "export PYTHONIOENCODING=utf8" >> ~/.bash_profile` so that the environment variable is set automatically when you launch the terminal.

Hopefully this should fix your issues.

**Comment by vdalv** [comment]
Followed your instructions and its working fine now, thanks. I didn't have a .bash_profile, but followed [these instructions](https://superuser.com/questions/602872/how-do-i-modify-my-git-bash-profile-in-windows) to create one.

Side-note: Looks like the letters (R, B) are appearing in color mode, not sure if this is desirable.
![](http://i.imgur.com/67aOQ1y.png)

When players are sharing a spot: (I like the color effects, nice to see you've handled this case already)
![](http://i.imgur.com/fPw9Z8M.png)

**Comment by MichaelOultram** [comment]
I disabled the letters in coloured mode as it isn't necessary for them to display.
