### ISSUE TITLE
Cards not in order

### ISSUE THREAD

**Issue by vdalv** [MichaelOultram/Labyrinth#4]
![](http://i.imgur.com/hXrqBL6.png)
![](http://i.imgur.com/Ttu7o8w.png)
Note: 'gem' was removed before 'map'
![](http://i.imgur.com/n6jeAw8.png)

Also note: I suck at this game.

Related: from what I recall, players should only be able to see their top card? I imagine this output is from earlier debugging, is that how you plan to leave it? So that players can know their opponent's cards and try to sabotage em?

If not, maybe there should be a 'Show top card' option, or something like that?

**Comment by MichaelOultram** [comment]
As with every board game, people have house rules which I wanted to try and cover in my implementation. The list of rules that I could think of are [here](https://github.com/MichaelOultram/Labyrinth/blob/5bd488b9e3c9858f0330b547fb6366799d81e1a5/labyrinth.py#L10), but not all of them are implemented correctly yet.

I have made a push that implements `CARDS_IN_ORDER` (enabled by default) so that 'gem' won't be removed before 'map'.  This seems to have made the "AI" a bit more dumb, so you may have more of a chance at beating it. `MOVE_AFTER_PICKUP` is currently enabled (I haven't written the code to disable it yet), so players (and the AI) can get all their cards and back home to win the game in one move (only if they are very lucky).

`SEE_ALL_CARDS` is also implemented which will hide the opponents cards. One side-effect of enabling `SEE_ALL_CARDS` and `CARDS_IN_ORDER` together is you'll be able to see all your cards even though `CARDS_IN_ORDER` normally hides your other cards.

There is also a way to configure the rules when running the program (although most of them don't really do anything yet), but since the changes are not saved (yet), you'll probably want to just change it in the [code](https://github.com/MichaelOultram/Labyrinth/blob/5bd488b9e3c9858f0330b547fb6366799d81e1a5/labyrinth.py#L10)

**Comment by vdalv** [comment]
Cool, thanks. Sorry for the late reply.
